development:
  adapter: postgresql
  encoding: unicode
  database: adnan_dental_db
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: adnan_dental_db
  pool: 5
  username: postgres
  password: 123
